# Generated by Django 6.0.6 on 2026-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_purchasehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Учень'), ('parent', 'Батьки'), ('adult', 'Випускник / Дорослий'), ('teacher', 'Вчитель / Репетитор')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_grade',
            field=models.CharField(blank=True, choices=[('5', '5 клас'), ('6', '6 клас'), ('7', '7 клас'), ('8', '8 клас'), ('9', '9 клас'), ('10', '10 клас'), ('11', '11 клас'), ('nmt', 'Підготовка до НМТ / Вступ'), ('self', 'Для саморозвитку / Викладання')], max_length=20, null=True, verbose_name='Цільовий клас / Мета'),
        ),
    ]
