# Generated by Django 6.0.6 on 2026-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_phone_number_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Учень'), ('parent', 'Батьки / Опікун'), ('adult', 'Випускник / Дорослий'), ('teacher', 'Вчитель / Репетитор')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
