# Generated by Django 6.0.6 on 2026-07-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='included_materials',
            field=models.ManyToManyField(blank=True, to='materials.studymaterial', verbose_name='Матеріали, що входять у пакет'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_bundle',
            field=models.BooleanField(default=False, verbose_name='Це Пакет (Bundle)'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Безкоштовний матеріал'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл матеріалу'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубліковано на вітрині'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Ціна (UAH)'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='tags',
            field=models.ManyToManyField(blank=True, to='materials.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва тегу'),
        ),
    ]
