# Generated by Django 6.0.6 on 2026-07-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Назва теми НМТ (напр. 'Планіметрія')")),
                ('recommended_materials', models.ManyToManyField(blank=True, to='materials.studymaterial', verbose_name='Рекомендовані конспекти')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('CHOICE', "Один з п'яти (1-15)"), ('MATCH', 'Відповідність (16-18)'), ('SHORT', 'Коротка відповідь (19-22)')], default='CHOICE', max_length=10, verbose_name='Тип завдання')),
                ('text', models.TextField(verbose_name='Текст запитання')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnostic_questions/', verbose_name='Картинка (якщо є)')),
                ('correct_short_answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Відповідь (тільки для 19-22 завдань)')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.diagnostictopic', verbose_name='Тема')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name="Текст варіанту (напр. '5 см' або 'А')")),
                ('is_correct', models.BooleanField(default=False, verbose_name='Це правильна відповідь?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='materials.question')),
            ],
        ),
    ]
