# Generated by Django 6.0.6 on 2026-07-14 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_diagnostictopic_question_answeroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Це правильна відповідь? (тільки для CHOICE)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('CHOICE', "Один з п'яти (1 бал)"), ('MATCH', 'Відповідність (до 3 балів)'), ('SHORT', 'Коротка відповідь (2 бали)')], default='CHOICE', max_length=10, verbose_name='Тип завдання'),
        ),
        migrations.CreateModel(
            name='MatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name="Умова (ліва колонка, напр. '1. Функція парна')")),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.answeroption', verbose_name='Правильний варіант (А-Д)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_items', to='materials.question', verbose_name='Завдання')),
            ],
        ),
    ]
