# Generated by Django 6.0.6 on 2026-07-31 07:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_answeroption_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('bot', 'Telegram-бот')], default='web', max_length=10, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/', verbose_name='Файл матеріалу'),
        ),
    ]
