# Generated by Django 6.0.6 on 2026-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_order_source_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис матеріалу'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material_images/', verbose_name='Обкладинка (Фото)'),
        ),
    ]
