# Generated by Django 6.0.6 on 2026-08-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_studymaterial_description_studymaterial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, default="Авторський конспект від освітнього проєкту «До Квадрату» — це ваш надійний помічник для успішного складання НМТ з математики. Матеріал створений з урахуванням 7-річного досвіду викладання та містить лише найголовніше: структуровану теорію без зайвої води, усі необхідні базові формули, алгоритми розв'язання та детальний розбір типових практичних завдань. Ідеально підходить як для самостійного вивчення теми з нуля, так і для швидкого повторення перед іспитом.", null=True, verbose_name='Опис матеріалу'),
        ),
    ]
