# Generated by Django 6.0.6 on 2026-08-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_studymaterial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='HTML Презентація'),
        ),
    ]
