# Generated by Django 6.0.6 on 2026-09-03 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_studymaterial_html_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Базовий (Легкий)'), (2, 'Стандартний (Середній)'), (3, 'Профільний (Складний)')], default=2, verbose_name='Складність'),
        ),
        migrations.AddField(
            model_name='question',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='practice_questions', to='materials.studymaterial', verbose_name='Теги (До яких уроків належить)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.diagnostictopic', verbose_name='Тема (для діагностики)'),
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Набрано балів')),
                ('max_score', models.PositiveIntegerField(default=18, verbose_name='Максимум балів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проходження')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='materials.studymaterial', verbose_name='Тема (Урок)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спроба проходження',
                'verbose_name_plural': 'Спроби проходження',
                'ordering': ['-created_at'],
            },
        ),
    ]
