# Generated by Django 6.0.6 on 2026-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_question_difficulty_question_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='svg_code',
            field=models.TextField(blank=True, null=True, verbose_name='SVG код малюнка (пріоритетніше за картинку)'),
        ),
    ]
