# Generated by Django 6.0.6 on 2026-09-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_tutorstudentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudentrequest',
            name='course',
            field=models.CharField(choices=[('nmt', 'Підготовка до НМТ (10-11 клас)'), ('grade_7', 'Математика (7 клас)'), ('grade_8', 'Математика (8 клас)'), ('grade_9', 'Математика (9 клас)'), ('other', 'Індивідуальні заняття')], default='nmt', max_length=20, verbose_name='Напрямок / Клас'),
        ),
    ]
