# Generated by Django 6.0.6 on 2026-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_tutorstudentrequest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorstudentrequest',
            name='course',
            field=models.CharField(choices=[('nmt', 'Підготовка до НМТ'), ('grade_5', 'Математика (5 клас)'), ('grade_6', 'Математика (6 клас)'), ('grade_7', 'Математика (7 клас)'), ('grade_8', 'Математика (8 клас)'), ('grade_9', 'Математика (9 клас)'), ('grade_10', 'Математика (10 клас)'), ('other', 'Закінчив/Закінчила школу')], default='nmt', max_length=20, verbose_name='Напрямок / Клас'),
        ),
    ]
