# Generated by Django 6.0.6 on 2026-09-12 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_alter_tutorstudentrequest_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐ (5/5)'), (4, '⭐⭐⭐⭐ (4/5)'), (3, '⭐⭐⭐ (3/5)'), (2, '⭐⭐ (2/5)'), (1, '⭐ (1/5)')], default=5, verbose_name='Оцінка')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено (показувати на сайті)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='materials.studymaterial', verbose_name='Матеріал (пусто = загальний відгук)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор відгуку')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
    ]
