# Generated by Django 6.0.6 on 2026-09-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Дата/Назва уроку (напр. 20.09.2026)')),
                ('html_content', models.TextField(verbose_name='HTML Презентація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_presentations', to=settings.AUTH_USER_MODEL, verbose_name='Учень')),
            ],
            options={
                'verbose_name': 'Індивідуальний урок',
                'verbose_name_plural': 'Індивідуальні уроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
