# Generated by Django 6.0.6 on 2026-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_review_reviewer_name_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceattempt',
            name='answers_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Збережені відповіді'),
        ),
    ]
