# Generated by Django 6.0.6 on 2026-09-24 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_practiceattempt_answers_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Опис помилки')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('fixed', 'Виправлено'), ('rejected', 'Відхилено (Не помилка)')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата повідомлення')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='materials.question', verbose_name='Завдання')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Скарга на завдання',
                'verbose_name_plural': 'Скарги на завдання',
                'ordering': ['-created_at'],
            },
        ),
    ]
