# Generated by Django 6.0.6 on 2026-09-27 18:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_questionerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudentrequest',
            name='parent_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Токен для батьків'),
        ),
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заняття')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема уроку')),
                ('nush_modeling', models.PositiveIntegerField(default=0, verbose_name='Моделювання (1-12)')),
                ('nush_solving', models.PositiveIntegerField(default=0, verbose_name="Розв'язування (1-12)")),
                ('nush_analysis', models.PositiveIntegerField(default=0, verbose_name='Аналіз результатів (1-12)')),
                ('homework_status', models.CharField(choices=[('not_assigned', '⚪ Не задано'), ('not_submitted', '🔴 Не здано'), ('partial', '🟡 Виконано частково / з помилками'), ('completed', '🟢 Виконано повністю')], default='not_assigned', max_length=20, verbose_name='Домашнє завдання')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Коментар викладача')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='materials.tutorstudentrequest', verbose_name='Учень')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'ordering': ['-date'],
            },
        ),
    ]
