# Generated by Django 6.0.6 on 2026-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_tutorstudentrequest_parent_token_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Промокод'),
        ),
    ]
