TOPIC_NAME = "27. Первісна та інтеграл"
TASKS = [{'difficulty': 1,
  'options': [('А) $0 + C$', False),
              ('Б) $5x + C$', True),
              ('В) $x^5 + C$', False),
              ('Г) $5x$', False),
              ('Д) $\\frac{5x^2}{2} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = 5$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 1,
  'options': [('А) $4x^3 + C$', False),
              ('Б) $\\frac{x^5}{5} + C$', True),
              ('В) $x^5 + C$', False),
              ('Г) $\\frac{x^4}{4} + C$', False),
              ('Д) $5x^5 + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = x^4$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 1,
  'options': [('А) $\\ln x + C$', False),
              ('Б) $-\\frac{1}{x} + C$', True),
              ('В) $\\frac{1}{x} + C$', False),
              ('Г) $\\frac{2}{x^3} + C$', False),
              ('Д) $-\\frac{2}{x^3} + C$', False)],
  'svg_code': '',
  'text': 'Вкажіть первісну для функції $f(x) = \\frac{1}{x^2}$.',
  'topic_tags': ['27. Первісна та інтеграл', '3. Степені'],
  'type': 'CHOICE'},
 {'difficulty': 1,
  'options': [('А) $-\\sin x + C$', False),
              ('Б) $\\sin x + C$', True),
              ('В) $\\cos x + C$', False),
              ('Г) $-\\cos x + C$', False),
              ('Д) $\\operatorname{tg} x + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = \\cos x$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 1,
  'options': [('А) $e^x + C$', True),
              ('Б) $xe^{x-1} + C$', False),
              ('В) $\\frac{e^{x+1}}{x+1} + C$', False),
              ('Г) $e^x \\ln x + C$', False),
              ('Д) $e^{-x} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = e^x$.',
  'topic_tags': ['27. Первісна та інтеграл', '19. Показникові вирази'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $6x - 4 + C$', False),
              ('Б) $x^3 - 2x^2 + x + C$', True),
              ('В) $x^3 - 4x^2 + x + C$', False),
              ('Г) $3x^3 - 2x^2 + x + C$', False),
              ('Д) $x^3 - 2x^2 + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = 3x^2 - 4x + 1$.',
  'topic_tags': ['27. Первісна та інтеграл',
                 '4. Одночлени, многочлени та формули скороченого множення'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $2\\sqrt{x} + C$', True),
              ('Б) $\\sqrt{x} + C$', False),
              ('В) $-\\frac{1}{2x\\sqrt{x}} + C$', False),
              ('Г) $\\frac{1}{2\\sqrt{x}} + C$', False),
              ('Д) $\\ln\\sqrt{x} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = \\frac{1}{\\sqrt{x}}$.',
  'topic_tags': ['27. Первісна та інтеграл', '9. Корені та їх властивості'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $F(x) = x^2 + 2$', True),
              ('Б) $F(x) = x^2 + 1$', False),
              ('В) $F(x) = 2x^2 + 1$', False),
              ('Г) $F(x) = x^2 + 3$', False),
              ('Д) $F(x) = x^2 - 2$', False)],
  'svg_code': '',
  'text': 'Знайдіть ту первісну функції $f(x) = 2x$, графік якої проходить через '
          'точку $M(1; 3)$.',
  'topic_tags': ['27. Первісна та інтеграл', '11. Функції та їх властивості'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $9$', True),
              ('Б) $7$', False),
              ('В) $8$', False),
              ('Г) $15$', False),
              ('Д) $3$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_{-1}^2 3x^2 \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $0$', False),
              ('Б) $1$', True),
              ('В) $-1$', False),
              ('Г) $\\frac{\\pi}{2}$', False),
              ('Д) $2$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_0^{\\pi/2} \\cos x \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $e - 1$', False),
              ('Б) $1$', True),
              ('В) $0$', False),
              ('Г) $e$', False),
              ('Д) $\\frac{1}{e} - 1$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_1^e \\frac{1}{x} \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл', '20. Логарифмічні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $-\\cos(2x) + C$', False),
              ('Б) $-\\frac{1}{2}\\cos(2x) + C$', True),
              ('В) $\\frac{1}{2}\\cos(2x) + C$', False),
              ('Г) $-2\\cos(2x) + C$', False),
              ('Д) $2\\cos(2x) + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = \\sin(2x)$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $e^{3x-1} + C$', False),
              ('Б) $3e^{3x-1} + C$', False),
              ('В) $\\frac{1}{3}e^{3x-1} + C$', True),
              ('Г) $\\frac{1}{3}e^{3x} + C$', False),
              ('Д) $e^{3x} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = e^{3x-1}$.',
  'topic_tags': ['27. Первісна та інтеграл', '19. Показникові вирази'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $12$ м', True),
              ('Б) $16$ м', False),
              ('В) $8$ м', False),
              ('Г) $14$ м', False),
              ('Д) $10$ м', False)],
  'svg_code': '',
  'text': 'Тіло рухається прямолінійно зі швидкістю $v(t) = 3t^2 + 2t$ (м/с). '
          'Який шлях пройде тіло за перші $2$ секунди (від $t=0$ до $t=2$)?',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $F(x) = \\operatorname{tg} x + 1$', True),
              ('Б) $F(x) = \\operatorname{tg} x + 2$', False),
              ('В) $F(x) = \\operatorname{ctg} x + 1$', False),
              ('Г) $F(x) = \\operatorname{tg} x - 1$', False),
              ('Д) $F(x) = -\\operatorname{tg} x + 3$', False)],
  'svg_code': '',
  'text': 'Знайдіть ту первісну функції $f(x) = \\frac{1}{\\cos^2 x}$, графік '
          'якої проходить через точку $M(\\frac{\\pi}{4}; 2)$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $8$', False),
              ('Б) $9$', False),
              ('В) $\\frac{26}{3}$', True),
              ('Г) $26$', False),
              ('Д) $\\frac{28}{3}$', False)],
  'svg_code': '',
  'text': 'Обчисліть площу фігури, обмеженої лініями $y = x^2$, $y = 0$, $x = '
          '1$, $x = 3$.',
  'topic_tags': ['27. Первісна та інтеграл', '12. Квадратична функція'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $16$', False),
              ('Б) $8$', False),
              ('В) $0$', True),
              ('Г) $32$', False),
              ('Д) $4$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_{-2}^2 x^3 \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $\\frac{1}{2}$', False),
              ('Б) $\\frac{1}{3}$', True),
              ('В) $1$', False),
              ('Г) $\\frac{1}{4}$', False),
              ('Д) $\\frac{2}{3}$', False)],
  'svg_code': '',
  'text': 'Обчисліть площу фігури, обмеженої графіками функцій $y = \\sqrt{x}$ '
          'та $y = x^2$.',
  'topic_tags': ['27. Первісна та інтеграл',
                 '12. Квадратична функція',
                 '9. Корені та їх властивості'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $\\frac{(2x-1)^5}{5} + C$', False),
              ('Б) $\\frac{(2x-1)^5}{10} + C$', True),
              ('В) $4(2x-1)^3 + C$', False),
              ('Г) $8(2x-1)^3 + C$', False),
              ('Д) $\\frac{(2x-1)^5}{2} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = (2x-1)^4$.',
  'topic_tags': ['27. Первісна та інтеграл',
                 '4. Одночлени, многочлени та формули скороченого множення'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $2$', True),
              ('Б) $1$', False),
              ('В) $0$', False),
              ('Г) $\\frac{1}{2}$', False),
              ('Д) $-2$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_0^{\\pi} \\cos\\left(\\frac{x}{2}\\right) '
          '\\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $S$', False),
              ('Б) $-S$', True),
              ('В) $2S$', False),
              ('Г) $S^2$', False),
              ('Д) $0$', False)],
  'svg_code': '\n'
              '<svg viewBox="-1 -4 6 5" width="100%" height="200px" '
              'xmlns="http://www.w3.org/2000/svg">\n'
              '    <defs>\n'
              '        <marker id="arrInt1" viewBox="0 0 10 10" refX="8" '
              'refY="5" markerWidth="4" markerHeight="4" '
              'orient="auto-start-reverse"><path d="M 0 1 L 10 5 L 0 9 z" '
              'fill="#7f8c8d" /></marker>\n'
              '    </defs>\n'
              '    <line x1="-1" y1="0" x2="5" y2="0" stroke="#7f8c8d" '
              'stroke-width="0.05" marker-end="url(#arrInt1)"/>\n'
              '    <line x1="0" y1="1" x2="0" y2="-4" stroke="#7f8c8d" '
              'stroke-width="0.05" marker-end="url(#arrInt1)"/>\n'
              '    <text x="4.8" y="-0.2" font-size="0.3" '
              'font-family="sans-serif">x</text>\n'
              '    <text x="0.2" y="-3.8" font-size="0.3" '
              'font-family="sans-serif">y</text>\n'
              '    \n'
              '    <path d="M 1 0 L 1 -3 Q 2.5 -1 4 -3 L 4 0 Z" fill="rgba(243, '
              '156, 18, 0.3)" stroke="none"/>\n'
              '    <path d="M 0.5 -2.5 Q 2.5 -0.5 4.5 -3.5" fill="none" '
              'stroke="#3498db" stroke-width="0.08"/>\n'
              '    \n'
              '    <line x1="1" y1="0.1" x2="1" y2="-0.1" stroke="#333" '
              'stroke-width="0.04"/>\n'
              '    <text x="1" y="0.5" font-size="0.4" font-family="sans-serif" '
              'text-anchor="middle">a</text>\n'
              '    <line x1="4" y1="0.1" x2="4" y2="-0.1" stroke="#333" '
              'stroke-width="0.04"/>\n'
              '    <text x="4" y="0.5" font-size="0.4" font-family="sans-serif" '
              'text-anchor="middle">b</text>\n'
              '    \n'
              '    <text x="2.5" y="-1.5" font-size="0.6" '
              'font-family="sans-serif" text-anchor="middle" '
              'fill="#d35400">S</text>\n'
              '</svg>\n'
              '            ',
  'text': 'На рисунку зображено графік функції $y = f(x)$. Заштрихована фігура '
          'обмежена графіком цієї функції, віссю $Ox$ та прямими $x = a$, $x = '
          'b$. Відомо, що площа цієї фігури дорівнює $S$. Який із наведених '
          'виразів дорівнює $\\int_a^b f(x) \\, dx$?',
  'topic_tags': ['27. Первісна та інтеграл', '11. Функції та їх властивості'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $-\\frac{1}{x^3} + C$', True),
              ('Б) $-\\frac{12}{x^5} + C$', False),
              ('В) $\\frac{3}{x^3} + C$', False),
              ('Г) $-\\frac{3}{x^3} + C$', False),
              ('Д) $\\frac{1}{x^3} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = '
          '\\frac{3}{x^4}$.',
  'topic_tags': ['27. Первісна та інтеграл', '3. Степені'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $\\frac{2}{3}$', True),
              ('Б) $0$', False),
              ('В) $-\\frac{2}{3}$', False),
              ('Г) $\\frac{8}{3}$', False),
              ('Д) $4$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_{-1}^1 (x^2 - 4x) \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'CHOICE'},
 {'difficulty': 2,
  'options': [('А) $5^x \\ln 5 + C$', False),
              ('Б) $\\frac{5^x}{\\ln 5} + C$', True),
              ('В) $\\frac{5^{x+1}}{x+1} + C$', False),
              ('Г) $5^x + C$', False),
              ('Д) $x \\cdot 5^{x-1} + C$', False)],
  'svg_code': '',
  'text': 'Знайдіть загальний вигляд первісних для функції $f(x) = 5^{x}$.',
  'topic_tags': ['27. Первісна та інтеграл', '19. Показникові вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $0$', False),
              ('Б) $1$', True),
              ('В) $\\frac{\\pi}{2}$', False),
              ('Г) $2$', False),
              ('Д) $-1$', False)],
  'svg_code': '',
  'text': 'Обчисліть площу фігури, обмеженої графіком функції $y = \\cos x$, '
          'віссю $Ox$ та прямими $x = 0$ і $x = \\frac{\\pi}{2}$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $\\cos x + \\sin x + C$', False),
              ('Б) $-\\cos x - \\sin x + C$', True),
              ('В) $\\cos x - \\sin x + C$', False),
              ('Г) $-\\cos x + \\sin x + C$', False),
              ('Д) $1 + C$', False)],
  'svg_code': '',
  'text': 'Вкажіть первісну для функції $f(x) = \\sin x - \\cos x$.',
  'topic_tags': ['27. Первісна та інтеграл', '17. Тригонометричні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $4{,}5$', True),
              ('Б) $9$', False),
              ('В) $3$', False),
              ('Г) $6$', False),
              ('Д) $7{,}5$', False)],
  'svg_code': '\n'
              '<svg viewBox="-3 -2 3 5" width="100%" height="200px" '
              'xmlns="http://www.w3.org/2000/svg">\n'
              '    <defs>\n'
              '        <marker id="arrInt2" viewBox="0 0 10 10" refX="8" '
              'refY="5" markerWidth="4" markerHeight="4" '
              'orient="auto-start-reverse"><path d="M 0 1 L 10 5 L 0 9 z" '
              'fill="#7f8c8d" /></marker>\n'
              '    </defs>\n'
              '    <line x1="-3" y1="0" x2="2.5" y2="0" stroke="#7f8c8d" '
              'stroke-width="0.05" marker-end="url(#arrInt2)"/>\n'
              '    <line x1="0" y1="1.5" x2="0" y2="-4.5" stroke="#7f8c8d" '
              'stroke-width="0.05" marker-end="url(#arrInt2)"/>\n'
              '    \n'
              '    <path d="M -2 0 Q -0.5 -3.5 1 -3 Z" fill="rgba(243, 156, 18, '
              '0.3)" stroke="none"/>\n'
              '    <path d="M -2.5 2.25 Q 0 -4 2.5 2.25" fill="none" '
              'stroke="#3498db" stroke-width="0.08"/>\n'
              '    <line x1="-2.5" y1="0.5" x2="1.5" y2="-3.5" stroke="#e74c3c" '
              'stroke-width="0.08"/>\n'
              '    \n'
              '    <circle cx="-2" cy="0" r="0.1" fill="#2c3e50"/>\n'
              '    <text x="-2.2" y="0.4" font-size="0.3" '
              'font-family="sans-serif">-2</text>\n'
              '    <circle cx="1" cy="-3" r="0.1" fill="#2c3e50"/>\n'
              '    <text x="1" y="0.4" font-size="0.3" '
              'font-family="sans-serif">1</text>\n'
              '</svg>\n'
              '            ',
  'text': 'На рисунку зображено графіки функцій $y = 4 - x^2$ та $y = x + 2$. '
          'Обчисліть площу заштрихованої фігури.',
  'topic_tags': ['27. Первісна та інтеграл',
                 '12. Квадратична функція',
                 '15. Системи рівнянь'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $1$', False),
              ('Б) $2$', True),
              ('В) $3$', False),
              ('Г) $4$', False),
              ('Д) $1{,}5$', False)],
  'svg_code': '',
  'text': 'Тіло рухається прямолінійно зі швидкістю $v(t) = '
          '\\frac{1}{\\sqrt{t}}$. Знайдіть шлях, який пройшло тіло від $t=1$ до '
          '$t=4$.',
  'topic_tags': ['27. Первісна та інтеграл', '9. Корені та їх властивості'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $e$', True),
              ('Б) $e - 1$', False),
              ('В) $e + 1$', False),
              ('Г) $2e$', False),
              ('Д) $e^2$', False)],
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_0^1 (e^x + 2x) \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл', '19. Показникові вирази'],
  'type': 'CHOICE'},
 {'difficulty': 3,
  'options': [('А) $\\frac{x^4}{4} - \\frac{1}{x} + C$', False),
              ('Б) $3x^2 - \\frac{1}{x}$', True),
              ('В) $x^2 - x$', False),
              ('Г) $3x^2 - \\ln x$', False),
              ('Д) $3x^2 + \\frac{1}{x}$', False)],
  'svg_code': '',
  'text': 'Якщо $F(x) = x^3 - \\ln x$ є первісною для функції $f(x)$, то $f(x) '
          '= $ ',
  'topic_tags': ['27. Первісна та інтеграл',
                 '26. Похідна',
                 '20. Логарифмічні вирази'],
  'type': 'CHOICE'},
 {'difficulty': 1,
  'matches': [('1. $f(x) = x$', 'Д) $\\frac{x^2}{2} + C$'),
              ('2. $f(x) = \\cos x$', 'В) $\\sin x + C$'),
              ('3. $f(x) = x^2$', 'А) $\\frac{x^3}{3} + C$')],
  'options': ['А) $\\frac{x^3}{3} + C$',
              'Б) $-\\cos x + C$',
              'В) $\\sin x + C$',
              'Г) $x^2 + C$',
              'Д) $\\frac{x^2}{2} + C$'],
  'svg_code': '',
  'text': 'Узгодьте функцію (1–3) із загальним виглядом її первісних (А–Д).',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'MATCH'},
 {'difficulty': 2,
  'matches': [('1. $\\int_0^2 3x^2 \\, dx$', 'Д) $8$'),
              ('2. $\\int_1^3 x \\, dx$', 'В) $4$'),
              ('3. $\\int_0^2 (2x+1) \\, dx$', 'Г) $6$')],
  'options': ['А) $2$', 'Б) $3$', 'В) $4$', 'Г) $6$', 'Д) $8$'],
  'svg_code': '',
  'text': 'Узгодьте визначений інтеграл (1–3) із його значенням (А–Д).',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'MATCH'},
 {'difficulty': 2,
  'matches': [('1. $f(x) = e^x$', 'В) $F(x) = e^x - 1$'),
              ('2. $f(x) = \\cos x$', 'Б) $F(x) = \\sin x$'),
              ('3. $f(x) = -\\sin x$', 'Г) $F(x) = \\cos x - 1$')],
  'options': ['А) $F(x) = x^2 - 1$',
              'Б) $F(x) = \\sin x$',
              'В) $F(x) = e^x - 1$',
              'Г) $F(x) = \\cos x - 1$',
              'Д) $F(x) = x^3$'],
  'svg_code': '',
  'text': 'Узгодьте функцію $f(x)$ (1–3) із первісною $F(x)$, графік якої '
          'проходить через початок координат $(0;0)$ (А–Д).',
  'topic_tags': ['27. Первісна та інтеграл', '11. Функції та їх властивості'],
  'type': 'MATCH'},
 {'difficulty': 3,
  'matches': [('1. $f(x) = \\cos(2x)$', 'А) $\\frac{1}{2}\\sin(2x) + C$'),
              ('2. $f(x) = e^{3x}$', 'В) $\\frac{1}{3}e^{3x} + C$'),
              ('3. $f(x) = 3x-1$', 'Д) $\\frac{1}{6}(3x-1)^2 + C$')],
  'options': ['А) $\\frac{1}{2}\\sin(2x) + C$',
              'Б) $-\\frac{1}{2}\\cos(2x) + C$',
              'В) $\\frac{1}{3}e^{3x} + C$',
              'Г) $\\frac{1}{3}(3x-1)^2 + C$',
              'Д) $\\frac{1}{6}(3x-1)^2 + C$'],
  'svg_code': '',
  'text': 'Узгодьте складену функцію (1–3) з її первісною (А–Д).',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'MATCH'},
 {'answer': '-4',
  'difficulty': 3,
  'svg_code': '',
  'text': 'Обчисліть інтеграл $\\int_{-1}^3 (2x - 3) \\, dx$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'SHORT'},
 {'answer': '36',
  'difficulty': 3,
  'svg_code': '',
  'text': 'Обчисліть площу фігури, обмеженої лініями $y = 6x - x^2$ та $y = 0$.',
  'topic_tags': ['27. Первісна та інтеграл', '12. Квадратична функція'],
  'type': 'SHORT'},
 {'answer': '14',
  'difficulty': 3,
  'svg_code': '',
  'text': 'Для функції $f(x) = 3x^2 + 2x$ знайдіть первісну $F(x)$, графік якої '
          'проходить через точку $M(-1; 2)$. У відповідь запишіть значення '
          '$F(2)$.',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'SHORT'},
 {'answer': '9',
  'difficulty': 3,
  'svg_code': '',
  'text': 'Тіло рухається прямолінійно зі швидкістю $v(t) = 4t - t^2$ (м/с). '
          'Який шлях пройде тіло за перші 3 секунди від початку руху?',
  'topic_tags': ['27. Первісна та інтеграл'],
  'type': 'SHORT'}]